// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyffqhutawzplmcdbnvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5ZmZxaHV0YXd6cGxtY2RibnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjgyMzEsImV4cCI6MjA2NjAwNDIzMX0.6885iTZhDGBhbz8tcq5zmFgp2VY-XfRFkvmL4cGxMkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);